default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        types: [python]

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]
        args: [--check]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check,--profile=black]